# everything regarding where the asset folders are located

[Data]

images        = "images"
backgrounds   = "images/bg"
cgbackgrounds = "images/cg"
fonts         = "font/en"
music         = "bgm"
sounds        = "sfx"

[Defaults]

# entrypoint .script of a new game
startupscript = "options"
startuplabel  = "[Main]"

# various default images for the engine/game
selectsound =           "choice_hover"
a_button_image =        "gui/button_a.rgba32"
b_button_image =        "gui/button_b.rgba32"
start_button_image =    "gui/button_start.rgba32"

[Scripts]

#show debug info on screen
debug = true

[Fonts]

#fonts and styles that will be used in GUI
mainfont = 1
mainfontstyle = 1
titlefont = 1
titlefontstyle = 1

#font data to load and assign

font1 = "SpecialElite"
font1_color0text     = 0xFFFFFFFF
font1_color0outline  = 0x00000000
font1_color1text     = 0xFFFFFFFF
font1_color1outline  = 0x00000000
font1_color2text     = 0xFFFFFFFF
font1_color2outline  = 0x00000000